name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone OpenIM Server
        run: |
          git clone https://github.com/openimsdk/openim-docker
          cd openim-docker
          export OPENIM_IP=$(curl ifconfig.me)
          export LOG_STORAGE_LOCATION="../logs/"
          make init
          docker compose up -d

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest main.py

      - name: Build Docker Image
        run: docker build . -t my-test-image

      - name: Run Docker Container
        run: docker run my-test-image
